services:
  postgres:
    image: "postgres:14"
    container_name: "postgres"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  smart-restaurant-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart_restaurant_app_container
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - app_network

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - postgres
    ports:
      - "8181:8080"
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data: