# Use uma imagem base do OpenJDK
#FROM openjdk:11-jre-slim

# Defina o diretório de trabalho dentro do contêiner
#WORKDIR /app

# Copie o arquivo JAR do aplicativo para o contêiner
#COPY target/smartrestaurant.jar /app/smartrestaurant.jar

# Porta em que o aplicativo Spring Boot será executado
#EXPOSE 8080

# Comando para executar o aplicativo Spring Boot
#ENTRYPOINT ["java", "-jar", "/app/smartrestaurant.jar"]